(1-3)中級 Eメール重複チェック
yamada-organization/ex-emp-management-bugfix pull request #29
Opened 2023-06-09 07:05 UTC by yamada-kensyu

レビューよろしくお願いします

2023-06-09 07:13 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2023-06-09 07:13 UTC, igamasayuki commented on src/main/java/com/example/controller/AdministratorController.java
> +			model.addAttribute("emailExistError", "このメールアドレスは既に使われています");
　今回のエラーメッセージの登録ですが、
　model.addAttribute("キー", "エラーメッセージ");
　ではなく、resultにエラーメッセージを追加することができます。
　このようにすると、viewでは
　「○○を入力してください」
　というformのvalidateエラーが出る箇所に、今回のものと共通でエラーメッセージを出すことができます。
　BindingResultのAPIマニュアルを見ながら探してみてください。

2023-06-09 07:13 UTC, igamasayuki commented on src/main/java/com/example/controller/AdministratorController.java
> +		}
Exceptionで例外をキャッチしていると重複以外の例外もEメールの重複エラーとして振る舞われてしまいます。

以下の方針に修正をお願い致します。

今回の対応は、入力値チェックと同じようなタイミング(コントローラの最初の方)でチェックを終わらせるようにしてください。

上でチェックしてから問題なければ正常処理を行うイメージです。
※今回はtry-catchで囲みません

2023-06-09 08:24 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2023-06-09 08:24 UTC, igamasayuki commented on src/main/java/com/example/controller/AdministratorController.java
> +		}
処理自体は問題ありませんが、
if (result.hasErrors()) {
 return toInsert();
}
この処理が上に書かれていると、入力値エラーが全部解消した後に、メールアドレス重複チェックのエラー(or パスワード不一致のエラー)が出ることになるため、全部のエラーメッセージが同時に出るように改修をお願いします。

意味がわからない場合はご相談いただくか、終わっている人に聞いてみてください。

2023-06-09 08:58 UTC, yamada-kensyu commented
1-5でご指摘いただいたインデントのずれも合わせて修正いたしました

2023-06-12 00:16 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2023-06-12 00:16 UTC, igamasayuki commented on src/main/java/com/example/controller/AdministratorController.java
> +		if (administratorRepository.findByMailAddress(form.getMailAddress()) != null) {
ControllerではRpositoryを直接呼ばず、Serviceのメソッドを介して呼ぶようにしてください。
※AdministratorServiceにseachByMailAddress()を新規に作るイメージです。

2023-06-12 00:49 UTC, igamasayuki approved these changes
とてもわかりやすくなったと思います。
承認します。

2023-06-12 00:49 UTC, merged